### ISSUE TITLE
RSA magic bytes seem to be incorrect

### ISSUE THREAD

**Issue by hugomrdias** [oddsdk/ts-odd#519] opened 2023-05-13 09:26 UTC
am i missing something here ? the magic bytes for rsa seem incorrect.

https://github.com/oddsdk/ts-odd/blob/36c5e95467e6f38044ebf18422e47442e039aad1/src/components/crypto/implementation/browser.ts#L92-L95

```js
// multicodec code for rsa-pub https://github.com/multiformats/multicodec/blob/master/table.csv#L163
const code = 0x1205
const bytes = new Uint8Array([0x85, 0x24])
```

**Comment by matheus23** [comment] 2023-05-15 06:48
When this code was written, there was no multiformat code for RSA, so we chose something in the "free range" (and I think we may have incorrectly encoded the varint back then).

This needs to be fixed, the code in ts-ucan is correct. The problem is mainly it'll break stuff :) 

https://github.com/ucan-wg/ts-ucan/blob/b9188fcf5a4dc505aef46fd60ef24546f73be1a7/packages/default-plugins/src/prefixes.ts#L18-L21

**Comment by hugomrdias** [comment] 2023-05-15 11:00
Thank you @matheus23 and @icidasset for the explanation.
Is it encoding DER ANS1 `RSAPublicKey` ? Sizes seems to not match either

**Comment by matheus23** [comment] 2023-05-15 13:16
@hugomrdias I don't remember the specific name ATM. I think both the old and the new format are ASN DER, but one encodes SubjectPublicKeyInfo or something like that and the other encodes PublicKeyInfo.
I think the ts-ucan code has all the details regarding the old format, too (it has awkward backwards compat code for that).

**Comment by icidasset** [comment] 2023-06-02 01:16
Going to close this one, when we switch to the fission-server/ucans it'll be fixed.

**Closed by icidasset** 2023-06-02 01:16 UTC
